image: growingdata/grwdt-build-gcp:1.0.2

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

  # If we are using a linux / kuberenetes execution engine
  DOCKER_HOST: tcp://localhost:2375
  # If we are using a Winfows based runner
  # DOCKER_HOST: tcp://docker.for.win.localhost:2375

  DOCKER_TLS_CERTDIR: ""

  GIT_SUBMODULE_STRATEGY: normal # do not recursively set up submodules.  We have istio-cni as a submodule.
  GIT_DEPTH: "3"
  CICD_VERSION: "1.0.2"

###############################################################
###  Build, for building base images!
###############################################################
build:
  stage: build
  # only:
  #   - master
  script:
    # Pack and push GrowingData.Utilities
    - dotnet pack ./src/GrowingData.Utilities/GrowingData.Utilities.csproj -o ./pkg --include-symbols --include-source --nologo --version-suffix -p:PackageVersion="$(PACKAGE_VERSION)-beta-$(CI_JOB_ID)"
    - dotnet nuget push ./pkg/GrowingData.Utilities.$(PACKAGE_VERSION)-beta-$(CI_JOB_ID).nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
    - dotnet nuget push ./pkg/GrowingData.Utilities.$(PACKAGE_VERSION)-beta-$(CI_JOB_ID).symbols.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json

    # Pack and push GrowingData.Data
    - dotnet pack ./src/GrowingData.Data/GrowingData.Data.csproj -o ./pkg --include-symbols --include-source --nologo --version-suffix -p:PackageVersion="$(PACKAGE_VERSION)-beta-$(CI_JOB_ID)"
    - dotnet nuget push ./pkg/GrowingData.Data.$(PACKAGE_VERSION)-beta-$(CI_JOB_ID).nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
    - dotnet nuget push ./pkg/GrowingData.Data.$(PACKAGE_VERSION)-beta-$(CI_JOB_ID).symbols.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json

release:
  stage: release
  only:
    - tags
  script:
    # Pack and push GrowingData.Utilities
    - dotnet pack ./src/GrowingData.Utilities/GrowingData.Utilities.csproj -o ./pkg --include-symbols --include-source --nologo -p:PackageVersion=$(CI_COMMIT_TAG)
    - dotnet nuget push ./pkg/GrowingData.Utilities.$(CI_COMMIT_TAG).nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
    - dotnet nuget push ./pkg/GrowingData.Utilities.$(CI_COMMIT_TAG).symbols.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json

    # Pack and push GrowingData.Data
    - dotnet pack ./src/GrowingData.Data/GrowingData.Data.csproj -o ./pkg --include-symbols --include-source --nologo --version-suffix -p:PackageVersion="$(CI_COMMIT_TAG)"
    - dotnet nuget push ./pkg/GrowingData.Data.$(CI_COMMIT_TAG).nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
    - dotnet nuget push ./pkg/GrowingData.Data.$(CI_COMMIT_TAG).symbols.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
